# Generated by Django 2.2.9 on 2020-01-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commenr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commenr',
            new_name='Comment',
        ),
    ]
